#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

from playwright.sync_api import sync_playwright
from browser_prep import launch_persistent_context_with_retry, select_login_browser
from dy_core import PROFILE_ROOT, looks_logged_in
from dy_utils import is_valid_cookie_name


DATA_DIR = Path.home() / ".local" / "share" / "chaunydy-skill"
COOKIE_JSON = DATA_DIR / "cookies.json"
COOKIE_TXT = DATA_DIR / "cookies.txt"
USER_DATA_DIR = DATA_DIR / "browser-profile"


def ensure_dirs() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    USER_DATA_DIR.mkdir(parents=True, exist_ok=True)


def to_netscape(cookies: list[dict]) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by chaunydy-skill.",
        "",
    ]
    for cookie in cookies:
        domain = str(cookie.get("domain", "") or "").strip()
        if not domain:
            continue
        name = str(cookie.get("name", "") or "").strip()
        if not is_valid_cookie_name(name):
            continue
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(cookie.get("path", "/") or "/")
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires_value = cookie.get("expires", 0)
        try:
            expires_int = int(expires_value or 0)
        except Exception:
            expires_int = 0
        if expires_int < 0:
            expires_int = 0
        expires = str(expires_int)
        value = str(cookie.get("value", "") or "")
        lines.append("\t".join([domain, include_subdomains, path, secure, expires, name, value]))
    return "\n".join(lines) + "\n"

def login_and_export_cookies(requested_browser: str = "auto", timeout_seconds: int = 300, emit_progress: bool = True) -> dict:
    ensure_dirs()

    def emit(message: str) -> None:
        if emit_progress:
            print(message)

    try:
        launch_plan = select_login_browser(PROFILE_ROOT, USER_DATA_DIR, requested_browser=requested_browser)
    except Exception as exc:
        payload = {"success": False, "message": str(exc)}
        emit(json.dumps(payload, ensure_ascii=False, indent=2))
        return payload

    emit("Preparing dedicated browser environment for Douyin login.")
    emit(
        json.dumps(
            {
                "requested_browser": launch_plan["requested_browser"],
                "selected_browser": launch_plan["selected_browser"],
                "playwright_channel": launch_plan["playwright_channel"],
                "system_executable": launch_plan["system_executable"],
                "user_data_dir": launch_plan["user_data_dir"],
                "browser_scan": launch_plan["browser_scan"],
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    emit("Attempting to open the dedicated Douyin login window now.")
    emit("Do not continue unless you personally see a browser window on your desktop.")
    emit(f"I will keep checking cookies for up to {timeout_seconds} seconds.")

    deadline = time.time() + max(timeout_seconds, 30)
    try:
        with sync_playwright() as p:
            context = launch_persistent_context_with_retry(p, selected_browser=launch_plan, headless=False)
            page = context.new_page()
            page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=120000)
            page.wait_for_timeout(3000)
            emit(
                json.dumps(
                    {
                        "success": True,
                        "window_ready": True,
                        "selected_browser": launch_plan["selected_browser"],
                        "user_data_dir": launch_plan["user_data_dir"],
                        "current_url": page.url,
                        "page_title": page.title(),
                        "human_action_required": "Please log in in the visible Douyin window. If no window is visible, stop and report that explicitly.",
                    },
                    ensure_ascii=False,
                    indent=2,
                )
            )

            exported = False
            while time.time() < deadline:
                page.wait_for_timeout(5000)
                cookies = context.cookies()
                if looks_logged_in(cookies):
                    COOKIE_JSON.write_text(json.dumps(cookies, ensure_ascii=False, indent=2), encoding="utf-8")
                    COOKIE_TXT.write_text(to_netscape(cookies), encoding="utf-8")
                    emit(f"Exported cookies to:\n- {COOKIE_JSON}\n- {COOKIE_TXT}")
                    exported = True
                    break

            if not exported:
                emit("Timed out before a stable Douyin cookie set was observed.")
                context.close()
                return {
                    "success": False,
                    "window_ready": True,
                    "selected_browser": launch_plan["selected_browser"],
                    "user_data_dir": launch_plan["user_data_dir"],
                    "message": "Timed out before a stable Douyin cookie set was observed.",
                }

            emit("You can close the browser window now.")
            context.close()
            return {
                "success": True,
                "window_ready": True,
                "selected_browser": launch_plan["selected_browser"],
                "user_data_dir": launch_plan["user_data_dir"],
                "cookie_json": str(COOKIE_JSON),
                "cookie_txt": str(COOKIE_TXT),
            }
    except Exception as exc:
        payload = {
            "success": False,
            "window_ready": False,
            "selected_browser": launch_plan["selected_browser"],
            "user_data_dir": launch_plan["user_data_dir"],
            "message": str(exc),
            "human_action_required": "If no browser window appeared, stop here and report that the login window never became visible.",
        }
        emit(json.dumps(payload, ensure_ascii=False, indent=2))
        return payload


def main() -> int:
    parser = argparse.ArgumentParser(description="Open Douyin in a browser and export cookies after login.")
    parser.add_argument("--timeout-seconds", type=int, default=300)
    parser.add_argument("--browser", default="auto", help="Preferred dedicated browser: auto, chrome, edge, chromium")
    args = parser.parse_args()

    result = login_and_export_cookies(requested_browser=args.browser, timeout_seconds=args.timeout_seconds, emit_progress=True)
    return 0 if result.get("success") else 1


if __name__ == "__main__":
    raise SystemExit(main())
