#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

from playwright.sync_api import sync_playwright
from dy_utils import is_valid_cookie_name


DATA_DIR = Path.home() / ".local" / "share" / "chaunydy-skill"
COOKIE_JSON = DATA_DIR / "cookies.json"
COOKIE_TXT = DATA_DIR / "cookies.txt"
USER_DATA_DIR = DATA_DIR / "browser-profile"


def ensure_dirs() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    USER_DATA_DIR.mkdir(parents=True, exist_ok=True)


def to_netscape(cookies: list[dict]) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by chaunydy-skill.",
        "",
    ]
    for cookie in cookies:
        domain = str(cookie.get("domain", "") or "").strip()
        if not domain:
            continue
        name = str(cookie.get("name", "") or "").strip()
        if not is_valid_cookie_name(name):
            continue
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(cookie.get("path", "/") or "/")
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires_value = cookie.get("expires", 0)
        try:
            expires_int = int(expires_value or 0)
        except Exception:
            expires_int = 0
        if expires_int < 0:
            expires_int = 0
        expires = str(expires_int)
        value = str(cookie.get("value", "") or "")
        lines.append("\t".join([domain, include_subdomains, path, secure, expires, name, value]))
    return "\n".join(lines) + "\n"


def looks_logged_in(cookies: list[dict]) -> bool:
    names = {cookie.get("name", "") for cookie in cookies}
    domains = " ".join(cookie.get("domain", "") for cookie in cookies)
    return (
        any(name in names for name in ["sessionid", "sid_tt", "passport_csrf_token"])
        or "douyin.com" in domains
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Open Douyin in a browser and export cookies after login.")
    parser.add_argument("--timeout-seconds", type=int, default=300)
    args = parser.parse_args()

    ensure_dirs()

    print("Opening a persistent browser for Douyin login.")
    print("Please log in manually in the opened browser window.")
    print(f"I will keep checking cookies for up to {args.timeout_seconds} seconds.")

    deadline = time.time() + max(args.timeout_seconds, 30)
    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(
            user_data_dir=str(USER_DATA_DIR),
            headless=False,
        )
        page = context.new_page()
        page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=120000)

        exported = False
        while time.time() < deadline:
            page.wait_for_timeout(5000)
            cookies = context.cookies()
            if looks_logged_in(cookies):
                COOKIE_JSON.write_text(json.dumps(cookies, ensure_ascii=False, indent=2), encoding="utf-8")
                COOKIE_TXT.write_text(to_netscape(cookies), encoding="utf-8")
                print(f"Exported cookies to:\n- {COOKIE_JSON}\n- {COOKIE_TXT}")
                exported = True
                break

        if not exported:
            print("Timed out before a stable Douyin cookie set was observed.")
            context.close()
            return 1

        print("You can close the browser window now.")
        context.close()
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
